"""
AgriSentry - Member 3
Edge Gateway & LoRaWAN Telemetry Simulator

Simulates:
- Multiple farm sensor nodes
- Village community gateway
- LoRaWAN RF metadata
- MQTT-style telemetry publishing
- Offline in-memory message bus
- Serial frame encoding/decoding
"""

from __future__ import annotations

import json
import random
import re
import time
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from typing import Callable, Optional

from .config import (
    DEFAULT_GATEWAY_ID,
    DEFAULT_SENSOR_NODES,
    MQTT_HOST,
    MQTT_PORT,
    MQTT_TOPIC,
    LORAWAN_FREQUENCY_MIN,
    LORAWAN_FREQUENCY_MAX,
    SPREADING_FACTORS,
    RSSI_MIN,
    RSSI_MAX,
    SNR_MIN,
    SNR_MAX,
)





@dataclass
class SensorTelemetry:
    """Telemetry generated by a farm sensor node."""

    node_id: str
    gateway_id: str

    soil_moisture: float
    soil_temperature: float
    canopy_humidity: float
    battery_level: float

    timestamp: str

    frequency_mhz: float
    spreading_factor: int
    rssi_dbm: int
    snr_db: float




@dataclass
class SerialTelemetry:
    """Decoded serial telemetry frame."""

    node_id: str
    soil_moisture: float
    soil_temperature: float




class InMemoryMessageBus:
    """
    Lightweight internal message bus.

    Used when an external MQTT broker is unavailable.
    """

    def __init__(self):
        self.messages: list[dict] = []
        self.subscribers: list[Callable[[dict], None]] = []

    def subscribe(self, callback: Callable[[dict], None]) -> None:
        """Register a subscriber."""

        self.subscribers.append(callback)

    def publish(
        self,
        topic: str,
        payload: dict,
    ) -> None:
        """Publish a message internally."""

        message = {
            "topic": topic,
            "payload": payload,
            "timestamp": datetime.now(
                timezone.utc
            ).isoformat(),
        }

        self.messages.append(message)

        for subscriber in self.subscribers:
            subscriber(message)

    def get_messages(self) -> list[dict]:
        """Return all messages."""

        return list(self.messages)

    def clear(self) -> None:
        """Clear stored messages."""

        self.messages.clear()





class FarmSensorNode:
    """Simulated agricultural sensor node."""

    def __init__(
        self,
        node_id: str,
        gateway_id: str = DEFAULT_GATEWAY_ID,
    ):
        self.node_id = node_id
        self.gateway_id = gateway_id

    def generate_telemetry(self) -> SensorTelemetry:
        """Generate realistic agricultural telemetry."""

        return SensorTelemetry(
            node_id=self.node_id,
            gateway_id=self.gateway_id,

            soil_moisture=round(
                random.uniform(15.0, 45.0),
                2,
            ),

            soil_temperature=round(
                random.uniform(20.0, 35.0),
                2,
            ),

            canopy_humidity=round(
                random.uniform(45.0, 90.0),
                2,
            ),

            battery_level=round(
                random.uniform(50.0, 100.0),
                2,
            ),

            timestamp=datetime.now(
                timezone.utc
            ).isoformat(),

            frequency_mhz=round(
                random.uniform(
                    LORAWAN_FREQUENCY_MIN,
                    LORAWAN_FREQUENCY_MAX,
                ),
                3,
            ),

            spreading_factor=random.choice(
                SPREADING_FACTORS
            ),

            rssi_dbm=random.randint(
                RSSI_MIN,
                RSSI_MAX,
            ),

            snr_db=round(
                random.uniform(
                    SNR_MIN,
                    SNR_MAX,
                ),
                2,
            ),
        )





def calculate_checksum(data: str) -> str:
    """
    Calculate a simple hexadecimal checksum.

    XOR is used for lightweight serial simulation.
    """

    checksum = 0

    for character in data:
        checksum ^= ord(character)

    return f"{checksum:02X}"


def encode_serial_frame(
    node_id: str,
    soil_moisture: float,
    soil_temperature: float,
) -> str:
    """
    Convert telemetry into an AGRI serial frame.

    Example:

    $AGRI,NODE1,MOIST:24.8,TEMP:28.4*CS
    """

    body = (
        f"AGRI,{node_id},"
        f"MOIST:{soil_moisture:.1f},"
        f"TEMP:{soil_temperature:.1f}"
    )

    checksum = calculate_checksum(body)

    return f"${body}*{checksum}"





def decode_serial_frame(frame: str) -> SerialTelemetry:
    """
    Decode an AGRI serial frame.
    """

    pattern = (
        r"^\$AGRI,"
        r"(?P<node>[^,]+),"
        r"MOIST:(?P<moist>[0-9.]+),"
        r"TEMP:(?P<temp>[0-9.]+)"
        r"\*(?P<checksum>[0-9A-Fa-f]{2})$"
    )

    match = re.match(pattern, frame.strip())

    if not match:
        raise ValueError(
            "Invalid AGRI serial frame."
        )

    body = frame.strip()[1:frame.strip().rfind("*")]

    expected_checksum = calculate_checksum(body)

    received_checksum = match.group(
        "checksum"
    ).upper()

    if expected_checksum != received_checksum:
        raise ValueError(
            "Serial frame checksum mismatch."
        )

    return SerialTelemetry(
        node_id=match.group("node"),
        soil_moisture=float(
            match.group("moist")
        ),
        soil_temperature=float(
            match.group("temp")
        ),
    )



class VillageGateway:
    """
    Simulated village community gateway.

    One gateway serves multiple farm sensor nodes.
    """

    def __init__(
        self,
        gateway_id: str = DEFAULT_GATEWAY_ID,
        mqtt_host: str = MQTT_HOST,
        mqtt_port: int = MQTT_PORT,
    ):
        self.gateway_id = gateway_id
        self.mqtt_host = mqtt_host
        self.mqtt_port = mqtt_port

        self.nodes: list[FarmSensorNode] = []

        self.message_bus = InMemoryMessageBus()

        self.transport = "IN-MEMORY"

        self.packets_received = 0

    def add_node(
        self,
        node: FarmSensorNode,
    ) -> None:
        """Add a sensor node to the gateway."""

        self.nodes.append(node)

    def receive_packet(
        self,
        telemetry: SensorTelemetry,
    ) -> None:
        """Receive a telemetry packet."""

        self.packets_received += 1

        payload = asdict(telemetry)

        self.message_bus.publish(
            MQTT_TOPIC,
            payload,
        )

    def broadcast_once(self) -> list[SensorTelemetry]:
        """
        Generate one telemetry packet from every node
        and send it through the internal message bus.
        """

        packets = []

        for node in self.nodes:

            telemetry = node.generate_telemetry()

            self.receive_packet(
                telemetry
            )

            packets.append(
                telemetry
            )

        return packets

    def get_ingested_messages(self) -> list[dict]:
        """Return telemetry received by the gateway."""

        return self.message_bus.get_messages()





def try_mqtt_connection(
    host: str = MQTT_HOST,
    port: int = MQTT_PORT,
    timeout: float = 1.0,
) -> bool:
    """
    Check whether an MQTT broker is available.

    The simulator does not require MQTT to succeed.
    """

    try:
        import socket

        with socket.create_connection(
            (host, port),
            timeout=timeout,
        ):
            return True

    except Exception:
        return False




def create_default_gateway() -> VillageGateway:
    """
    Create the default Barabanki village gateway
    with three farm sensor nodes.
    """

    gateway = VillageGateway()

    for node_id in DEFAULT_SENSOR_NODES:

        gateway.add_node(
            FarmSensorNode(
                node_id=node_id,
                gateway_id=gateway.gateway_id,
            )
        )

    # Try MQTT, but always fall back safely.
    if try_mqtt_connection(
        gateway.mqtt_host,
        gateway.mqtt_port,
    ):
        gateway.transport = "MQTT"
    else:
        gateway.transport = "IN-MEMORY"

    return gateway





def run_gateway_demo() -> None:
    """Run a simple gateway demonstration."""

    gateway = create_default_gateway()

    print("\n==========================================")
    print("AGRISENTRY - EDGE GATEWAY SIMULATOR")
    print("==========================================")

    print(
        f"Gateway      : "
        f"{gateway.gateway_id}"
    )

    print(
        f"MQTT Broker  : "
        f"{gateway.mqtt_host}:{gateway.mqtt_port}"
    )

    print(
        f"Transport    : "
        f"{gateway.transport}"
    )

    print(
        f"Nodes        : "
        f"{len(gateway.nodes)}"
    )

    print("\nTELEMETRY")
    print("------------------------------------------")

    packets = gateway.broadcast_once()

    for packet in packets:

        print(
            f"\n{packet.node_id}"
        )

        print(
            f"  Soil Moisture : "
            f"{packet.soil_moisture}%"
        )

        print(
            f"  Soil Temp     : "
            f"{packet.soil_temperature} °C"
        )

        print(
            f"  Canopy Humid. : "
            f"{packet.canopy_humidity}%"
        )

        print(
            f"  Battery       : "
            f"{packet.battery_level}%"
        )

        print(
            f"  Frequency     : "
            f"{packet.frequency_mhz} MHz"
        )

        print(
            f"  Spreading F.  : "
            f"SF{packet.spreading_factor}"
        )

        print(
            f"  RSSI          : "
            f"{packet.rssi_dbm} dBm"
        )

        print(
            f"  SNR           : "
            f"{packet.snr_db} dB"
        )

    print("\nINGESTION")
    print("------------------------------------------")

    print(
        f"Packets received: "
        f"{gateway.packets_received}"
    )

    print(
        f"Messages stored : "
        f"{len(gateway.get_ingested_messages())}"
    )

    print("\nSERIAL FRAME TEST")
    print("------------------------------------------")

    frame = encode_serial_frame(
        "NODE1",
        24.8,
        28.4,
    )

    print(
        f"Encoded: {frame}"
    )

    decoded = decode_serial_frame(
        frame
    )

    print(
        f"Decoded: "
        f"{decoded}"
    )

    print("\n==========================================")
    print("EDGE GATEWAY SIMULATION COMPLETE")
    print("==========================================")


if __name__ == "__main__":
    run_gateway_demo()